version: "3.9"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pixelspring
    ports:
      - "5433:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - pixelspringnetwork

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
    ports:
      - "15432:80"
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - pixelspringnetwork

  sbootapp:
    build:
      dockerfile: Dockerfile
      context: ./pixelspringapi
    container_name: pixelspringapi
    restart: on-failure
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - pixelspringnetwork
    env_file: ./pixelspringapi/.env

  app:
    build:
      dockerfile: Dockerfile
      context: ./pixelspring
    container_name: pixelspring
    restart: on-failure
    depends_on:
      - sbootapp
    ports:
      - "3000:3000"
    networks:
      - pixelspringnetwork
    expose:
      - 3000

networks:
  pixelspringnetwork:
    driver: bridge

volumes:
  pgadmin_data:
